### ISSUE TITLE
Style & other fixes

### ISSUE THREAD

**Issue by Lorak-mmk** [Lorak-mmk/jnp1#1]
Line numbers are respective to commit https://github.com/Lorak-mmk/jnp1/commit/210b185fdfcf13fc65cf3a88a6afc2377134ef73

>2: `#include <cfloat>`

That is a C library, what do we need it for? It's my understanding that we should be trying to use modern C++ in this project.
>4: `#include <stdlib>`

Such library doesn't exist. Did you mean cstdlib? If so, again, it's C library, do we need it?

>8: `pair<int, int>;`
>9: `unordered_map<string, time_point>;`
>10: `tuple<string, double, time_point>;`
>12: `vector<string, int>;`
>20: `unordered_map<int, stops> courses;`
>21: `vector<single_tickets> tickets;`
>33: `vector<string> buy_tickets(int travel_time) {`
>35: `vector<string> best_tickets;`

As we are not using `using namespace std`, everything from STL should be prefixed by `std::`, so instead of `pair<int, int>;`, we should write `std::pair<int, int>;`, otherwise it won't compile. That applies to all lines mentioned here (I may have missed some).

>38: `get<2> tickets[i];`
>39: `get<1> tickets[i];`
>43: `get<0> tickets[i]`
>50: `get<0> tickets[0]`

std::get is a function, which means we need to use () to call it. So instead of `get<2> tickets[i];` we need to write  `get<2>(tickets[i]);`

> 40: `if (ok_czas_biletu`
> 48: `if (ok_czas biletow`

Let's stick to one naming convention - so variable names should be in English. Also, second usage of this variable (line 48) uses wrong name - missing underscore. BTW this variable isn't declared or assigned anywhere, so this code will most likely not work as intended.

>20: `unordered_map<int, stops> courses;`
>21: `vector<single_tickets> tickets;`

Let's not use global non-const variables. This is most likely too pedantic of me, as those look just like temporary definitions until creating `main` function, but this is just to not forget to move it after.

> 51: `best_tickers.push_back smallest_cost = summed_cost`

This line doesn't make much sense.

Also, it would be great if you could use clang-format to format code before commiting. I put clang-format.sh script in repo to make that easier. Just type ./clang-format.sh in terminal.

**Comment by Lorak-mmk** [comment]
>20: `unordered_map<int, stops> courses;`

What would you think about using long long instead of int? There may be test cases in which number exceeds int capacity.

**Comment by esculapa** [comment]
I will change my code, but remember - it was not finished version
